
import classes from './Layout.module.scss'
import cn from 'classnames'
import { ILayoutTypes } from './AuthTypes';
import { ReactNode } from 'react';


export const metadata = {
  title: "Auth page",
  description: "Generated by create next app",
};

const AuthLayout = ({children}:{children:ReactNode})=> {
  
  return (
    <div className={cn(classes.layout)}>
      {children}
    </div>
  );
}

export default AuthLayout
