
import classes from './layout.module.scss'
import cn from 'classnames'
import { ILayoutTypes } from './AuthTypes';
import LayoutWithMain from '../HOC/LayoutWithMain';


export const metadata = {
  title: "Auth page",
  description: "Generated by create next app",
};

const AuthLayout:React.FC<ILayoutTypes> = ({children})=> {
  
  return (
    <div className={cn(classes.layout)}>
      {children}
    </div>
  );
}

export default LayoutWithMain(AuthLayout)
