
import { Inter } from "next/font/google";
import classes from './SiteLayout.module.scss'
import cn from 'classnames'
import Footer from "@/app/(site)/(content)/components/Footer/Footer";
import Header from "@/app/(site)/(content)/components/Header/Header";
import Sidebar from "@/app/(site)/(content)/components/Sidebar/Sidebar";
import Menu  from "@/app/components/Menu/Menu";



const inter = Inter({
   style: "normal",
   subsets: ["latin"]
});

export const metadata = {
   title: "Pages",
   description: "Generated by create next app",
};

function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   return (
      <div className={cn(classes.wrapper)}>
         <Header>Header</Header>
         <Sidebar>
            {/* @ts-expect-error Server Component */}
            <Menu />
         </Sidebar>
         <div className={cn(classes.layout)}>
            {children}
         </div>
         <Footer>Footer</Footer>
      </div>
   );
}

export default RootLayout